f=show_simple_stats request handler
N-E-W-E-R-T-H/SKELETON-KING pull request #9
Opened 2023-04-27 06:24 UTC by korDen

2023-04-28 17:38 UTC, mrhappyasthma commented on SKELETON-KING/Program.cs
> +using ZORGATH;
When you rebase this PR , you can now remove all local using directives. I added global Using.cs.

2023-04-30 02:35 UTC, cptwonton commented on ZORGATH/SrpAuthResponse.cs
> +﻿using PhpSerializerNET;
nit: now that we're using a using file, this shouldn't be necessary

2023-04-30 02:38 UTC, cptwonton commented on ZORGATH/PreAuthResponse.cs
> +    public readonly string Salt2;
i understand that the php property has to stay the same to retain compatibility but perhaps this is a good opportunity to improve the naming of these two variables from `Salt` and `Salt2` to something else? scratching my head at what this could be

2023-04-30 03:58 UTC, mrhappyasthma commented on ZORGATH/PreAuthResponse.cs
> +    public readonly string Salt2;
We sometimes call `Salt2` the `PasswordSalt` in other code. We could consider that naming here as well.

2023-05-04 04:13 UTC, cptwonton commented on ZORGATH/SrpAuthHandler.cs
> +        if (!_srpAuthSessions.Remove(login, out SrpAuthSessionData? srpAuthSessionData))
confused on why a remove is done here to check for the absence of the value over `ContainsKey`? i guess I must be missing the background for srpAuthSession

2023-05-04 04:13 UTC, cptwonton commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> +        Assert.IsInstanceOfType(result, typeof(NotFoundObjectResult));
since "login" does map to a value, this test is failing

2023-05-04 17:16 UTC, korDen commented on ZORGATH/SrpAuthHandler.cs
> +        if (!_srpAuthSessions.Remove(login, out SrpAuthSessionData? srpAuthSessionData))
We the session in pre_auth and we need to remove it in srpAuth so that the session doesn't stay there forever.
Remove() returns false if it failed to remove the session:
```bool actuallyRemoved = sessions.Remove(key);```
if it didn't actually remove the session, it means that the session wasn't there in the first place.
With concurrent data structures, Contains() may return true but then Remove() may theoretically return false so Contains() is both less reliable but also plain not necessary since we must check Remove() return value anyway.

One could check Contains before Remove():

`if (!Contains() || !Remove()) { /* error */ }`

but it's exactly the same as 

`if (!Remove()) { /* error */ }`

2023-05-04 17:33 UTC, korDen commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> +        Assert.IsInstanceOfType(result, typeof(NotFoundObjectResult));
Yes. Removed this test as its now an impossible scenario.

2023-05-07 19:58 UTC, mrhappyasthma commented on TRANSMUTANSTEIN/AuthResponseTest.cs
> +        Assert.AreEqual(AuthResponse.ComputeAuthHash(accountDetails.AccountId, accountDetails.Cookie, clientIpAddress), authResponse.AuthHash);
For line 148, I actually like having the hardcoded value. Otherwise this test could fail due to bugs in `ComputeAuthHash` which is independent of the code under test (or at best is an implementation detail).

It also makes the test easier to read, as you know exactly what the expected output should be rather than doing additional logic of a function call.

2023-05-07 19:59 UTC, mrhappyasthma commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> +﻿using ZORGATH;
Should this be in the global Using.cs?

2023-05-07 20:00 UTC, mrhappyasthma commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> -    public async Task TestSrpAuthAccountIsMissing()
Is this test case no longer needed? It's unclear why it was removed.

2023-05-07 20:01 UTC, mrhappyasthma commented on ZORGATH/AccountDetails.cs
> +        var identities = bountyContextFactory.CreateDbContext().Accounts.Where(account => account.User.Id == UserId).Select(account => new List<string>() { account.Name, account.AccountId.ToString()
Do we not need to `await` on these async calls? Does the use of the context factory handle that implicitly somehow?

2023-05-07 20:02 UTC, mrhappyasthma commented on ZORGATH/AccountDetails.cs
> +        var identities = bountyContextFactory.CreateDbContext().Accounts.Where(account => account.User.Id == UserId).Select(account => new List<string>() { account.Name, account.AccountId.ToString()
Oh I see this returns a task which we await on below. (It was unclear what the return type was because of `var`).

2023-05-07 20:04 UTC, mrhappyasthma commented on ZORGATH/AuthResponse.cs
> +    public static string ComputeAuthHash(int accountId, string cookie, string ip)
(similar to my comment above. I wouldn't expose this just to use it inside of the Auth tests. We could expose it so it can be unit tested itself in its own file, but from the Auth perspective it's an implementation detail)

2023-05-12 19:17 UTC, korDen commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> +﻿using ZORGATH;
This has been fixed upstream.

2023-05-12 19:17 UTC, korDen commented on TRANSMUTANSTEIN/AuthResponseTest.cs
> +        Assert.AreEqual(AuthResponse.ComputeAuthHash(accountDetails.AccountId, accountDetails.Cookie, clientIpAddress), authResponse.AuthHash);
This is coming from a diffbase. I'll address this in a separate PR.

2023-05-12 19:18 UTC, korDen commented on TRANSMUTANSTEIN/SrpAuthHandlerTest.cs
> -    public async Task TestSrpAuthAccountIsMissing()
Correct! This scenario is simply no longer possible. Basically, if pre_auth succeeded, there is no way that an Account is missing.

2023-05-12 19:18 UTC, korDen commented on ZORGATH/AuthResponse.cs
> +    public static string ComputeAuthHash(int accountId, string cookie, string ip)
This is coming from a diffbase. I'll address this in a separate PR.

2023-05-13 03:54 UTC, mrhappyasthma commented on ZORGATH/ShowSimpleStatsHandler.cs
> +                /* NumberOfHeroesOwned: */ 139,
suggestion: Can we pull this in to a constant at the top of this file with a meaningful name? (Or maybe we can actually add a TODO to compute this. In the off chance we ever decide to add heroes).

2023-05-13 03:54 UTC, mrhappyasthma commented on ZORGATH/ShowSimpleStatsHandler.cs
> +                /* SeasonId: */ 22,
Does this value matter? How is it used?

May be good to document it.

2023-05-13 03:57 UTC, mrhappyasthma requested changes
Do we want to add a simple unit test or two for ShowSimpleStatsHandler->HandleRequest

2023-05-13 06:41 UTC, korDen commented on ZORGATH/ShowSimpleStatsHandler.cs
> +                /* NumberOfHeroesOwned: */ 139,
Done.

2023-05-13 06:41 UTC, korDen commented on ZORGATH/ShowSimpleStatsHandler.cs
> +                /* SeasonId: */ 22,
Done.

2023-05-13 06:41 UTC, korDen commented
> Do we want to add a simple unit test or two for ShowSimpleStatsHandler->HandleRequest

Done!

2023-05-13 06:58 UTC, mrhappyasthma approved these changes

2023-05-13 07:30 UTC, merged